from collections import Counter
from datetime import datetime

SKIP_DIRS = frozenset({
    ".git", ".venv", "venv", "__pycache__", "node_modules", "dist", "build",
    ".ruff_cache", ".pytest_cache", ".mypy_cache", ".tox", "target", ".idea",
    ".vscode", "eggs",
})

STACK_FILES = {
    "pyproject.toml": "Python (pyproject)",
    "requirements.txt": "Python (requirements)",
    "setup.py": "Python (setuptools)",
    "package.json": "Node (package.json)",
    "Cargo.toml": "Rust (cargo)",
    "go.mod": "Go (modules)",
    "Gemfile": "Ruby (bundler)",
    "composer.json": "PHP (composer)",
    "pom.xml": "Java (maven)",
    "build.gradle": "Java (gradle)",
    "Dockerfile": "Docker",
    "Makefile": "Make",
}

MAX_FILES = 500
MAX_DEPTH = 4


def _walk(root, rel="", depth=0, collected=None):
    if collected is None:
        collected = []
    if depth > MAX_DEPTH or len(collected) >= MAX_FILES:
        return collected
    try:
        entries = sorted((root / rel).iterdir(), key=lambda p: (not p.is_dir(), p.name.lower()))
    except OSError:
        return collected
    for entry in entries:
        name = entry.name
        if name in SKIP_DIRS or name.endswith(".egg-info"):
            continue
        if name.startswith(".") and name != ".env.example":
            continue
        if len(collected) >= MAX_FILES:
            break
        if entry.is_dir():
            collected.append(f"{rel}{name}/")
            _walk(root, f"{rel}{name}/", depth + 1, collected)
        else:
            collected.append(f"{rel}{name}")
    return collected


def build_map(root):
    from pathlib import Path

    root = Path(root)
    stamp = datetime.now().strftime("%Y-%m-%d")
    try:
        names = {p.name for p in root.iterdir()}
    except OSError:
        names = set()
    stack = sorted({label for fname, label in STACK_FILES.items() if fname in names})
    files = _walk(root)
    exts = Counter("." + f.rsplit(".", 1)[-1].lower() if "." in f.rsplit("/", 1)[-1] else "(no ext)" for f in files if not f.endswith("/"))
    lines = [f"# Project map — {root.name} (generated by Hazzel, {stamp})", ""]
    lines.append(f"Stack: {', '.join(stack) if stack else 'unknown'}")
    lines.append(f"Files: {len([f for f in files if not f.endswith('/')])} shown (max {MAX_FILES}, depth {MAX_DEPTH})")
    lines.append("")
    lines.append("## Structure")
    lines.append("")
    lines.append("```")
    lines.extend(files or ["(empty)"])
    lines.append("```")
    lines.append("")
    if exts:
        lines.append("## By extension")
        lines.append("")
        for ext, count in exts.most_common(12):
            lines.append(f"- `{ext}` — {count}")
        lines.append("")
    lines.append("_Regenerate with `/init`. Edit freely — Hazzel reads this file for context._")
    lines.append("")
    return "\n".join(lines)
